#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE USER ${RODAN_POSTGRES_USER} PASSWORD '${RODAN_POSTGRES_PASSWORD}';
        CREATE DATABASE ${RODAN_POSTGRES_DB};
        GRANT ALL PRIVILEGES ON DATABASE ${RODAN_POSTGRES_DB} TO ${RODAN_POSTGRES_USER};
        ALTER USER ${RODAN_POSTGRES_USER} CREATEDB;
EOSQL
